### ISSUE TITLE
コマンド「**、ログ取得したい」でmodeというキーワードは存在しないと言われる

### ISSUE THREAD

**Issue by link1345** [link1345/LinkClamBot#27]
Error Code
```
Docker_LinkClanBot | 2021/08/22 16:17:00 : どちらのログが欲しいですか？
Docker_LinkClanBot | 2021/08/22 16:17:03 : 現行の音声チャンネルログイン生データです
Docker_LinkClanBot | 2021/08/22 16:17:13 : どちらのログが欲しいですか？
Docker_LinkClanBot | Ignoring exception in view <test_button timeout=180.0 children=2> for item <test_button_Button style=<ButtonStyle.secondary: 2> url=None disabled=False label='加工済みログ' emoji=None row=None>:
Docker_LinkClanBot | Traceback (most recent call last):
Docker_LinkClanBot |   File "/usr/local/lib/python3.9/site-packages/discord/ui/view.py", line 359, in _scheduled_task
Docker_LinkClanBot |     await item.callback(interaction)
Docker_LinkClanBot |   File "/root/opt/command/voice_log/interactive.py", line 161, in callback
Docker_LinkClanBot |     timeData = await Chart.makeTimeList(self.client, now_filepath , CSetting.OneMonthOutput_RoleID , mode="NAME")
Docker_LinkClanBot | TypeError: makeTimeList() got an unexpected keyword argument 'mode'
```

**Comment by link1345** [comment]
たぶん治った。くろーず
