### ISSUE TITLE
command.member_sheet.interactive_adminのonMessageで、項目が大杉と言われる

### ISSUE THREAD

**Issue by link1345** [link1345/LinkClamBot#28]
Error Code
```
Docker_LinkClanBot | Ignoring exception in on_message
Docker_LinkClanBot | Traceback (most recent call last):
Docker_LinkClanBot |   File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 350, in _run_event
Docker_LinkClanBot |     await coro(*args, **kwargs)
Docker_LinkClanBot |   File "/root/opt/base/base.py", line 41, in on_message
Docker_LinkClanBot |     await self.command.on_message(self.client, message)
Docker_LinkClanBot |   File "/root/opt/base/Command.py", line 208, in on_message
Docker_LinkClanBot |     await run(key, client, message)
Docker_LinkClanBot |   File "/root/opt/base/Command.py", line 154, in run
Docker_LinkClanBot |     await self.C_list[key]["object"].on_message(config=self.C_list[key], client=client, message=message)
Docker_LinkClanBot |   File "/root/opt/command/member_sheet/interactive_admin.py", line 106, in on_message
Docker_LinkClanBot |     self.eventButton = ListMenu( self, self.select_message )
Docker_LinkClanBot |   File "/root/opt/command/member_sheet/interactive_admin.py", line 67, in __init__
Docker_LinkClanBot |     self.add_item(ListMenu_SelectMenu(data,text))
Docker_LinkClanBot |   File "/root/opt/command/member_sheet/interactive_admin.py", line 54, in __init__
Docker_LinkClanBot |     self.add_option(label=item, default=defaultFlag)
Docker_LinkClanBot |   File "/usr/local/lib/python3.9/site-packages/discord/ui/select.py", line 228, in add_option
Docker_LinkClanBot |     self.append_option(option)
Docker_LinkClanBot |   File "/usr/local/lib/python3.9/site-packages/discord/ui/select.py", line 245, in append_option
Docker_LinkClanBot |     raise ValueError('maximum number of options already provided')
Docker_LinkClanBot | ValueError: maximum number of options already provided
```

**Comment by link1345** [comment]
discordのリファレンスに、「25項目以内にしろ」とかいてあった。
https://discord.com/developers/docs/interactions/message-components#select-menus

**Comment by link1345** [comment]
コミットするとき間違えて、#26 うんたらとか書いちゃった、てへぺろ。
とりあえず、書けたオワリ。

f0e09a6cfa3d55401e6e9eb3c51de2e020d8b95a
から
b1029c97e82dae8af43e8b01741d43e652113d80
は、このissuesの奴です。
