### ISSUE TITLE
command.member_sheet.check_consistencyで間違ったところを削除してしまう

### ISSUE THREAD

**Issue by link1345** [link1345/LinkClamBot#29]
sheetのID欄を消すと、その消したユーザーの項目が削除されず、その上の項目が消されしまう。
何か他にも問題ありそう…？

Error Code
```
Docker_LinkClanBot | Ignoring exception in on_message
Docker_LinkClanBot | Traceback (most recent call last):
Docker_LinkClanBot |   File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 350, in _run_event
Docker_LinkClanBot |     await coro(*args, **kwargs)
Docker_LinkClanBot |   File "/root/opt/base/base.py", line 41, in on_message
Docker_LinkClanBot |     await self.command.on_message(self.client, message)
Docker_LinkClanBot |   File "/root/opt/base/Command.py", line 208, in on_message
Docker_LinkClanBot |     await run(key, client, message)
Docker_LinkClanBot |   File "/root/opt/base/Command.py", line 154, in run
Docker_LinkClanBot |     await self.C_list[key]["object"].on_message(config=self.C_list[key], client=client, message=message)
Docker_LinkClanBot |   File "/root/opt/command/member_sheet/check_consistency.py", line 141, in on_message
Docker_LinkClanBot |     change_after  = self.changeData(old_user_row,  userList[ userList_id.index( sheet_col[num] ) ] , sheetIndexNumber )
Docker_LinkClanBot | ValueError: '' is not in list
```

**Comment by link1345** [comment]
直した。
